name = "TopoChains"
uuid = "61cb6e9c-cad8-11eb-0d06-599cf5a8288f"
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"

[compat]
julia = "^1.6"
MacroTools = "^0.5"
Functors = "^0.2"

[extras]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Flux"]
